name: app_with_apps
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  provider: ^6.0.5

dev_dependencies:
  bloc: ^8.1.2
  build_runner: ^2.4.7
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_getit: ^1.2.1
  flutter_lints: ^2.0.2
  flutter_localization: ^0.1.14
  flutter_svg: ^2.0.9
  flutter_test:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: any
  intl: ^0.18.0
  uuid: ^4.2.1

flutter:
  assets:
    - assets/
  uses-material-design: true
